### ISSUE TITLE
Update readme.md to include screenshots

### ISSUE THREAD

**Issue by rodrigoelp** [falahati/CircularProgressBar#1]
One thing I love about cocoapods (iOS reusable code sharing mechanism) is people tend to be quite explicative about what their code does/doesn't do.

Specially for their readme they invest into graphics that display the look and feel of the product as well as the customisation of the element.

Have you thought about improving the documentation by including these elements? I am pretty sure that it will be something to look forward in the nuget community.

**Comment by falahati** [comment]
Readme updated and screenshot added as part of the new update.
