### ISSUE TITLE
Control won't show up in the Toolbox

### ISSUE THREAD

**Issue by ghost** [falahati/CircularProgressBar#10]
I'm having problems to find the Control in my Toolbox. I added the package through nuget to my project that is made in .Net 3.5 and built it. But the Circular ProgressBar wont show up in my Toolbox.

'CircularProgressBar' and 'WinFormAnimation' do show up in my references, tho.

**Comment by PoxyDoxy** [comment]
You need to add the DLL to your Toolbox.

**Comment by ghost** [comment]
You mean with right click and 'Choose Items' ?

The Control also doesnt show up in there.

**Comment by PoxyDoxy** [comment]
Yes, you need to click "Browse" and Select the "CircularProgressBar.dll" in order for it to show up.

**Comment by falahati** [comment]
Also, please make sure to select the "CircularProgressBar.dll" file from your project's "Release" or "Debug" directory.
Don't use the one in the "package" directory as it fails to load because it needs to have the "WinFormAnimation.dll" file next to it.

**Comment by ghost** [comment]
Thanks alot, now it is working. Is that usual? because the readme tells it would auto add to the toolbox on build. (like usercontrols do)

**Comment by falahati** [comment]
Yeah, sry about that, I need to update the readme file to reflect new changes.

Controls should be added to toolbox automatically, however, in this case, because of a dependency and a case of incompatibility on Visual Studio and NuGet side, this doesn't happen automatically.

**Comment by jaime-olivares** [comment]
Please update the README. It will save us a lot of time.

**Comment by falahati** [comment]
Just tested with the new NuGet format and after signing with a strong name. This should no longer be a problem.
