### ISSUE TITLE
Grey border around the box

### ISSUE THREAD

**Issue by ghost** [falahati/CircularProgressBar#11]
When i have a black background color on the form, i see a box around the circle, as a container.
Is there any way for hide it?

Thanks and regards

**Comment by ghost** [comment]
Can have any solution? Need to know for use or not use...

**Comment by falahati** [comment]
Hey,
Change the background of the `Control` to transparent to remove the box.

Also, if you want to have a background picture behind it, you need to put the `Control` in a `Panel` and use the background image property of the parent `Panel`.

**Comment by ghost** [comment]
ok for the pic on background. Works fine.
i already have the background set to transparent:
![20170630_100316](https://user-images.githubusercontent.com/20864537/27727209-bde3f248-5d7d-11e7-94ea-288e571f3c9b.jpg)

**Comment by ghost** [comment]
Problem  with border solved once i put it inside a panel.

**Comment by jeranio** [comment]
Can you explain more how you got rid of border? Thanks

**Comment by ghost** [comment]
Sorry, 3 months later, i've used another one and i do not remember this...
Sorry again.
