### ISSUE TITLE
Border around progressbar

### ISSUE THREAD

**Issue by jeranio** [falahati/CircularProgressBar#12]
Hello,
There seems to be a square border around the progress bar not in preview but while application is running.
I have set the background to match mine but the border still remains.
![preview_mode](https://user-images.githubusercontent.com/11857624/31143283-201a386a-a87d-11e7-9e90-a7d0e36b7421.PNG)
![run_mode](https://user-images.githubusercontent.com/11857624/31143284-203e858a-a87d-11e7-965a-d71daec19a2a.PNG)

**Comment by jeranio** [comment]
I tried all the solution given on previous issue but none seems to work e.g.
Hey,
Change the background of the Control to transparent to remove the box.

Also, if you want to have a background picture behind it, you need to put the Control in a Panel and use the background image property of the parent Panel.

**Comment by falahati** [comment]
Can you provide a sample code?

**Comment by jeranio** [comment]
There is no code (only what the designer has generated). The circular bar was installed as a nuget package, I referenced the dll and added the custom control to my toolbox, added the control to my form and set the properties.

**Comment by falahati** [comment]
Unfortunately, I cant reproduce this behavior, that's why I asked for a sample project to test. Also, what is your OS version?

**Comment by WernerOvalle** [comment]
te mamasate mano

**Comment by DKR82** [comment]
I had the same problem, running a form with the circular progress bar control from within a scripting environment.
I solved it by explicitly enabling VisualStyles (**Application.EnableVisualStyles()**), which is enabled by default in a Visual Studio WinForms Application, but wasn´t enabled in my scripting environment.

**Comment by falahati** [comment]
If I cant reproduce a problem, I just can't simply fix it.
This is an open source project, go on and find the reason behind the problem and fix it if you can. This also helps other people out there.

**Comment by rao12345** [comment]
![Screenshot (13)](https://user-images.githubusercontent.com/29507328/99193102-c34e4480-279c-11eb-9268-3344483344b4.png)
Is there a solution to this problem? I faced this border issue while running windows form on raspberry pi using mono.
