### ISSUE TITLE
Progress Colors

### ISSUE THREAD

**Issue by ivanBorgo** [falahati/CircularProgressBar#13]
Using the progress bar several times (twice or more), setting its value, progressbar colors don't refresh.

Example
            CircularProgressBar1.Value = 0
            CircularProgressBar1.Text = CircularProgressBar1.Value.ToString

                CircularProgressBar1.Value = 10
                CircularProgressBar1.Text = CircularProgressBar1.Value.ToString

                CircularProgressBar1.Value = 30
                CircularProgressBar1.Text = CircularProgressBar1.Value.ToString

               'Resetting value
               CircularProgressBar1.Value = 0
               CircularProgressBar1.Text = CircularProgressBar1.Value.ToString
               CircularProgressBar1.Refresh()

First time works perfectly, from the second time the colors are not updated properly.

Thanks a lot
Best regards

**Comment by falahati** [comment]
Please clarify with some pictures. At this point, I have no idea about the problem.

**Comment by PoxyDoxy** [comment]
To confirm, the GUI thread is not locked when you update the second time?

**Comment by falahati** [comment]
Can't reproduce. Works as expected with the provided code.
