### ISSUE TITLE
Disable Animation

### ISSUE THREAD

**Issue by foreachthing** [falahati/CircularProgressBar#15]
Please allow to disable animation all together.
Update a copy process with lots of small files; the CircularProgressBar will lag a lot!

**Comment by falahati** [comment]
What happens if you set the animation duration to zero?

**Comment by falahati** [comment]
For older version, 

`circularProgressBar.AnimationSpeed = 1;`

And in the latest version as of now, 

`circularProgressBar.AnimationSpeed = 0;`

Should solve your problem. 
However, I am aware for some time that the underlying `WinFormAnimation` library needs an overhaul.
