### ISSUE TITLE
Not thread safe

### ISSUE THREAD

**Issue by KamilSzymborski** [falahati/CircularProgressBar#20]
I can't change many colors in the same time.

**Comment by falahati** [comment]
UserControls don't need to be thread safe. Always change properties in the main UI thread using the `Control.Invoke()` method.

**Comment by KamilSzymborski** [comment]
Oh, now i see: just deadlock. I locked on CircularProgressBar instance and u have lock on "this".

It's a bit of my mistake, I just blocked it quickly on this instance, just for testing.
Lock + this is bad idea, better create empty object for locking, if I can suggest : P

Thanks for fast reacton and help.
