### ISSUE TITLE
Can't add to VS 2017 with netframwork 4.5.2

### ISSUE THREAD

**Issue by 2pay** [falahati/CircularProgressBar#21]
Can't add to VS 2017 with netframwork 4.5.2.

**Comment by FoxBlood72** [comment]
Same for me, I think it's working just for 4.0

**Comment by falahati** [comment]
What is the error message?

**Comment by FoxBlood72** [comment]
when I'm trying to open the dll it shows me this error: http://prntscr.com/nuzibc

**Comment by falahati** [comment]
This should be solved by using the latest update of VS2017 and the latest version of NuGet and the package. In any case, I already described a workaround for this problem [here](https://github.com/falahati/CircularProgressBar/issues/10) as well as the readme file published with the NuGet package that will popup as soon as you install the package in VS.
