### ISSUE TITLE
cross thread issue  progress bar stop 

### ISSUE THREAD

**Issue by JuttDB** [falahati/CircularProgressBar#23]
i am using vs 2017 with winform.
circularProgressbar is working great but if i use thread.sleep method under button click then circularProgressbar hang.
is there any event that i can use that event to handle the update progressbar. 

i am using Marquee  style.

**Comment by falahati** [comment]
Please describe the situation more clearly. You have a CircularProgressbar working in Marquee style and another button with `thread.Sleep()` that results in this problem or they are somehow connected to each other? What you are trying to do that requires a `thread.Sleep()`; maybe I can suggest a workaround for the time being until I solve the problem with the progress bar.

**Comment by JuttDB** [comment]
i solved the problem. used the circularProgressbar in main thread and put all other process in background thread. so its working now.
