### ISSUE TITLE
Filling the ProgressColor is not always correct

### ISSUE THREAD

**Issue by nerndt** [falahati/CircularProgressBar#24]
g.FillPie(
                        new SolidBrush(ProgressColor),
                        ToRectangle(new RectangleF(point, size)),
                        _animatedStartAngle ?? StartAngle,
                        (_animatedValue ?? Value) / (Maximum - Minimum) * 360);

shoudl be

                    g.FillPie(
                        new SolidBrush(ProgressColor),
                        ToRectangle(new RectangleF(point, size)),
                        _animatedStartAngle ?? StartAngle,
                        (_animatedValue ?? (Value - Minimum)) / (Maximum - Minimum) * 360);

**Comment by falahati** [comment]
Thank you for reporting this. I will fix it with the next update.

**Comment by falahati** [comment]
fixed
