### ISSUE TITLE
Async void with MessageBox.Show() causes memory and thread leaks depending on the value of MessageBoxOptions.

### ISSUE THREAD

**Issue by t2-kob** [falahati/CircularProgressBar#25]
### Problem

Use one of the following options to display the popup on `async void` method, it cause Memory and Thread leakage.

- `MessageBoxOptions.DefaultDesktopOnly`
- `MessageBoxOptions.ServiceNotification`

Then, the pop-up will increase by **about one thread per second while the pop-up is being displayed.**

-----------------
### Environment info

- Windows10 Pro 1903
    - .Net Framework 4.8
    - .Net Core 3.1

-----------------
### Procedure to reproduce the problem
Create a new WinForms project, add one CircularProgressBar to the Form, and add an OnLoad event.
And change OnLoad method to `async void` and `await` something.

```csharp
private async void Form1_Load(object sender, EventArgs e)
{
    await Task.Delay(1000);
    MessageBox.Show("Not Leak", "01", MessageBoxButtons.OK, MessageBoxIcon.Error);  // Not Leak
    MessageBox.Show("Not Leak", "02", MessageBoxButtons.OK, MessageBoxIcon.Error, MessageBoxDefaultButton.Button1, MessageBoxOptions.RightAlign);  // Not Leak
    MessageBox.Show("Not Leak", "03", MessageBoxButtons.OK, MessageBoxIcon.Error, MessageBoxDefaultButton.Button1, MessageBoxOptions.RtlReading);  // Not Leak
    MessageBox.Show("Leak", "04", MessageBoxButtons.OK, MessageBoxIcon.Error, MessageBoxDefaultButton.Button1, MessageBoxOptions.DefaultDesktopOnly); // Leak
    MessageBox.Show("Leak", "05", MessageBoxButtons.OK, MessageBoxIcon.Error, MessageBoxDefaultButton.Button1, MessageBoxOptions.ServiceNotification); // Leak
    MessageBox.Show("Not Leak", "06", MessageBoxButtons.OK, MessageBoxIcon.Error);  // Not Leak
}
```

**Comment by falahati** [comment]
This seems to be unrelated to this project.
