### ISSUE TITLE
Deleting Marquee Progress bar causes Visual Studio 2010 to Crash.

### ISSUE THREAD

**Issue by PoxyDoxy** [falahati/CircularProgressBar#5]
If the progress bar is set as Marquee, It becomes extremely buggy, and causes Visual Studio 2010 to crash every single time you try to delete the progress bar. 

If you change the progress bar to Block or Continuous, and then delete the progress bar, it works fine.

Version 2.2.0 install using NuGet.

**Comment by falahati** [comment]
I look into this.

**Comment by falahati** [comment]
Please check the latest version.

**Comment by PoxyDoxy** [comment]
Thanks, I'll download the latest version through NuGet and try it tomorrow.
