### ISSUE TITLE
Setting Background to Transparent gives Error "Property value is not valid". 

### ISSUE THREAD

**Issue by PoxyDoxy** [falahati/CircularProgressBar#6]
With details "Value does not fall within the expected range.".

Using Visual Studio 2010, on .NET 4.0 

It does this for both version 2.1.0 and 2.2.0

Edit1: Just noticed a similar issue was created, defining this exact same issue. 
Apparently the reason it does not support Transparency, is because of AntiAliasing Reasons. 
While It might be fine to just use the background colour, it does not however fix the issue of overlapping Forms, Text, and other Circular Progress Bars, as the background will create a horrible Square over the progress bar. 
I will leave it up to falahati to either close or leave this issue open, until it is solved.

**Comment by falahati** [comment]
Please check the latest version.
It does support transparency by drawing the parent inside of the holes instead of clearing them. It does the work, however it is not very performance friendly.
