### ISSUE TITLE
Transparency issues with multiple objects

### ISSUE THREAD

**Issue by Zati** [falahati/CircularProgressBar#8]
First of, nice job with the progress bars, it has most of the functionality needed. However, I need to have a progress bar on top of another progress bar, thus making center transparent. Doing so results in an ultimate transparency where I get the background image instead of the progress bar laying behind. 
Is it possible in any other way to have two progress bars laying on top of each other having the circle graphs laying next to each other?

**Comment by falahati** [comment]
Hi Zati,

Transparency in WinForm is only valid based on parent-child relationship. So you can't get the output of a child as the background of another child. However, you can make one of them the parent of the other one and obtain the output you desire. This is however not always convenient and may not result in the output you want. But this is the best you can do to achieve the desired arrangement.
Now, doing this is not possible with the designer as the progress bar is not a container. But it is very simple to do in code:

```C#
circularProgressBar1.Controls.Add(circularProgressBar2);
circularProgressBar2.Location = new Point(10, 10);
```
