### ISSUE TITLE
Failed to create component 'CircularProgressBar'

### ISSUE THREAD

**Issue by saifmalik87** [falahati/CircularProgressBar#9]
Hi there,

I tried to load the Circular Progress Baron the form, I see this error. I have no idea how to fix this. I am using Visual Studio 2015 and using VB.NET.
![error](https://cloud.githubusercontent.com/assets/28601940/25906129/bc19c172-359b-11e7-92ea-973e35d45623.png)

Thank you

Regards,
Saif Malik

**Comment by falahati** [comment]
Hmm, I thought I solved that, let me take an other look

**Comment by falahati** [comment]
BTW, in the meantime, I think you can add the control directly from the code by editing the {Form}.Designer.vb file

**Comment by saifmalik87** [comment]
Thank you Soroush.

If I add the module in vb.net form, it lets me add it but won’t let me run the code and gives error shown in attached image.

I really liked your module and wanted to have a play with it but just can’t get it working. I did not understand what you meant by editing the code in designer.vb file. All I see there is that you are using system file dependencies, right?

Could you help me please to fix this for VB.NET?

Regards,
Saif Malik
![error2](https://cloud.githubusercontent.com/assets/28601940/25944101/02b486b4-363a-11e7-9ea1-82ac6f3383bd.png)

**Comment by falahati** [comment]
Can you send me a sample project file so I can reproduce the problem here? It seems to me that you have two different version of WinFormAnimation library in your project, and in fact, one of them might be outdated.

Latest version of WinFormAnimation is 1.5 but you are using 1.3

**Comment by saifmalik87** [comment]
Hi Soroush,

Yes, you are right but I was trying to play with the code to get it working but in vain. See the project file in a zip format from this link:

http://www1.zippyshare.com/v/YV20o95W/file.html

Many thanks for your help.

Regards,
Saif

**Comment by falahati** [comment]
It seems that you had an earlier version of the library in your project and then updated to the latest version. So some leftovers were carried over. Attached is the fixed version of your project.

What you had to do was to edit "Form1.Designer.vb" file and remove the line about the `Me.CircularProgressBar1.AnimationFunction` or replace it with the following:
`Me.CircularProgressBar1.AnimationFunction = KnownAnimationFunctions.Liner`
Also, you should edit the "Form1.resx" file and remove the lines throwing the error message. Also if you want to have the library in the toolbar, first compile your project and then add the library to the toolbar from the '/bin/Debug/CircularProgressBar.dll' address. Don't touch the references, they are ok.

[Test.zip](https://github.com/falahati/CircularProgressBar/files/998665/Test.zip)

Therefore, I close this issue.

**Comment by saifmalik87** [comment]
Thank you very much Soroush,

Yes, you are right. I followed your instructions and it works like a charm. Thank you for your help.

Regards,
Saif Malik

**Comment by falahati** [comment]
Good to hear Saif. Have a good time developing.
